name: Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: NixOS/nix-installer-action@main

      - name: Update Zephyr branch from ZMK
        run: |
          zmk_branch="$(sed -z -e 's/.*- *name: zmk\n *remote: zmkfirmware\n *revision: \([^\n]*\)\n.*/\1/' config/west.yml | cut -d'#' -f2 | tr -d ' ')"
          zephyr_branch="$(curl -sSfL https://github.com/zmkfirmware/zmk/raw/refs/heads/${zmk_branch:-main}/app/west.yml | sed -z -e 's/.*- *name: zephyr\n *remote: zmkfirmware\n *revision: \([^\n]*\)\n.*/\1/')"
          sed -zi \
            -e "s/\(- *name: zephyr\n *remote: zmkfirmware\n *revision: [0-9a-f]* *#\) [^\n]*\n/\1 $zephyr_branch\n/" \
            config/west.yml

      - run: nix -vL run --show-trace .#update

      - name: Instantiate flake template
        run: |
          mkdir ../zmk-config
          cd ../zmk-config
          git init
          nix flake init --template ../zmk-nix
          nix flake lock
          git add .

      - name: Update ZMK and Zephyr branches
        run: |
          zmk_branch="$(git ls-remote --refs https://github.com/zmkfirmware/zmk.git 'refs/tags/*' | cut -d/ -f3 | sort -rV | head -n1 | cut -d. -f1-2)-branch"
          zephyr_branch="$(curl -sSfL "https://github.com/zmkfirmware/zmk/raw/refs/heads/$zmk_branch/app/west.yml" | sed -z -e 's/.*- *name: zephyr\n *remote: zmkfirmware\n *revision: \([^\n]*\)\n.*/\1/')"
          sed -zi \
            -e "s/\(- *name: zmk\n *remote: zmkfirmware\n *revision: [0-9a-f]* *#\) [^\n]*\n/\1 $zmk_branch\n/" \
            -e "s/\(- *name: zephyr\n *remote: zmkfirmware\n *revision: [0-9a-f]* *#\) [^\n]*\n/\1 $zephyr_branch\n/" \
            config/west.yml
        working-directory: ../zmk-config

      - run: nix -vL run --show-trace .#update
        working-directory: ../zmk-config

      - name: Copy updated files to template directory in original checkout
        run: |
          (
            cd ../zmk-config

            IFS=$'\n'
            for file in $(git ls-files -m); do
              cp "$file" ../zmk-nix/template/"$file"
            done
          )
          rm -rf ../zmk-config

      - id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update_zmk_config_deps
          delete-branch: true
          committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          commit-message: 'config,nix: update deps'
          title: 'config,nix: update deps'
          labels: 'dependencies'
          body: |
            Automated bump of ZMK dependencies

      - uses: benc-uk/workflow-dispatch@v1
        if: ${{ contains(fromJSON('["created", "updated"]'), steps.create-pr.outputs.pull-request-operation) }}
        with:
          workflow: ci.yml
          ref: refs/heads/update_zmk_config_deps
